server:
  port: 5000
spring:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  profiles:
    include: aws # 배포용 설정
    # includ: secure # 로컬용 설정
  sql.init.mode: always